// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects which exact-tail compaction implementation to use when
 * `compact_preserve_recent_tokens` is active.
 */
export type CompactExactTailStrategy = "auto" | "remote_legacy" | "remote_v2" | "semantic_transcript";
