// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects how Codex keeps the model prompt within the active context window.
 */
export type PromptRetentionMode = "compact" | "rolling";
