// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects optional compaction behavior layered on top of rolling prompt retention.
 */
export type RollingCompactionMode = "disabled" | "pairwise";
